spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/esercizio81
    username: root
    password: claudio
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  application:
    name: esercizio-81-crud-test

---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true